services:
  autofactura:
    container_name: autofactura-sayer-app
    build:
      context: .
      dockerfile: Dockerfile
    image: autofactura-sayer-img:latest
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    extra_hosts:
      - "host.docker.internal:host-gateway"
